### ISSUE TITLE
Добавить название у всплывающей формы

### ISSUE THREAD

**Issue by mobyl** [birdkiwi/mod_simplecallback#1]
1. Как добавить название у всплывающей формы? Над полем "Имя".
2. Сделать, чтобы модуль на портретном отображении при маленькой высоте экрана (моб.версия) всплывал к верхней границе экрана (не видно капчи и кнопки "Отправить").

**Comment by birdkiwi** [comment]
Прошу проверить как работают заголовки:
https://github.com/birdkiwi/mod_simplecallback/commit/0345115a277d65d128c207eccc76b0b78be7d6c2
