### ISSUE TITLE
Поле для ввода в модальном окне?

### ISSUE THREAD

**Issue by MonsterDeveloper** [birdkiwi/mod_simplecallback#13]
После того как нажата кнопка "Отправить" появляется окно SweetAlert с полем для ввода?! В исходниках никак не могу найти метод с вызовом SweetAlert.
![image](https://user-images.githubusercontent.com/16190582/28331501-03264862-6bfa-11e7-9b6d-ea1047744271.png)

**Comment by birdkiwi** [comment]
Учитесь пользоваться поиском по файлам :)

**Comment by MonsterDeveloper** [comment]
Найс помощь (нет)

**Comment by birdkiwi** [comment]
Помочь погуглить как включить поиск в операционной системе?
