### ISSUE TITLE
Is there an update planned?

### ISSUE THREAD

**Issue by kosh2323** [birdkiwi/mod_simplecallback#28]
Hi, is there an update planned for Joomla 4 and PHP 8.1?

**Comment by birdkiwi** [comment]
Hi! I'm now more focused on development of my projects, so there are no plans to update this plugin, sorry!

**Comment by kosh2323** [comment]
> Hi! I'm now more focused on development of my projects, so there are no plans to update this plugin, sorry!

Hi, thank you for the answer, in any case, I wish you success.
