### ISSUE TITLE
после успешной отправки новое пустое окно

### ISSUE THREAD

**Issue by d-korolkov** [birdkiwi/mod_simplecallback#3]
Модуль один из немногих работает, но после успешной отправки запроса в новом окне пишет:

адресная строка: www........index.php?option=com_ajax&module=simplecallback&format=json

{«success»:true,«error»:false,«message»:«\u0421\u043f\u0430\u0441\u0438\u0431\u043e \u0437\u0430 \u0412\u0430\u0448 \u0438\u043d\u0442\u0435\u0440\u0435\u0441!»}

**Comment by birdkiwi** [comment]
Не должно новое окно открываться. Это значит, что не отрабатывает JS скрипт. Нужно смотреть в консоль браузера и отлавливать ошибку там.
