### ISSUE TITLE
Добавить возможность вставки кода Яндекс-Директа

### ISSUE THREAD

**Issue by SeBun** [birdkiwi/mod_simplecallback#9]
Часто этот модуль используется на одностраничниках, где нужно рассказать человеку о продукте и оставить форму для связи. При заполнении формы и ее успешной отправке выводится всплывающее окно с текстом, который задается в настройках модуля. Хотелось бы видеть там же возможность задать коды для Яндекс-Директ и Google-Adwords, так как в этом случае отправка формы является конечной целью.

**Comment by birdkiwi** [comment]
Как вариант можно повесить событие на отправку, чтобы у разработчика была возможность навесить свои функции.

**Comment by birdkiwi** [comment]
Добавил события, посмотрите, может будет полезно? Описание в Readme:
https://github.com/birdkiwi/mod_simplecallback/blob/master/README.md

https://github.com/birdkiwi/mod_simplecallback/releases/tag/1.7.0-beta
